package com.sit.abbra.abbraapi.enums;

public enum ColumnName {
	REQUEST_ID, SOURCE, REF_NO, REQUEST_DATE, DOC_NO, DOC_DATE, FEE_SLIP_NO, APO_DATE, APO_TIME, APO_CHECKPOINT,
	PRIORITY_DESC, PRIORITY, PASSPORT_NO, TM6_NO, PASSPORT_DATE, PASSPORT_EXPDATE, PASSPORT_PLACE, NATIONALITY,
	NAT_TNAME, PREFIXNM, OCC_DESC, EFIRSTNM, EFAMILYNM, EMIDDLENM, BIRTHDATE, BIRTHPLACE, GENDER, BUILDING, ADDRESS,
	ROAD, PV_NAME, AMP_NAME, TMB_NAME, POSTCODE, TEL, IN_DATE, IN_DEPTNAME, VISATYPE_NAME, VISA_DATE, VISA_EXPDATE,
	CONV_NAME, CONVREGNO, REASON_EXT, REASONEXTTNM, REASON_SEQNO, EXT_DAY, REF_PERSON, REF_TEL, PERSON_PIC,
	PASSPORT_PIC, REMARK_REVIEW, PREAPV_CHKPIBICS, PREAPV_CHKPIBICS_DATE, PREAPV_CHKPIBICS_USER, BL_REMARK,
	OFFICER_NAME, PREAPV_CHKPIBICS_REMARK, PREAPV_STATUS, PREAPV_PERMIT_DATE, PREAPV_NOPERMIT_DATE, WAITCOMMENT_SEQNO,
	WAITCOMMENT_OTH, PREAPV_REMARK, PREAPV_DATE, PREAPV_SEND_STATUS, PREAPV_SENDPB_STATUS, DOCUMENT_TYPE, LIST_NO,
	DOCUMENT_FILE_NAME, DOCUMENT_PATH, VISA_CATCUR, VISA_CATNEW, VISA_CATSUB, BLACKLIST_STS, REVIEW_DATE,
	CHK_BLACKLIST_CODE, CHK_BLACKLIST, CHKPB_DATE, CHKPB_BY, CHECK_PIBICS_ID, POSITIONNM, DEPTTNM, GLOBAL_DATA_CODE,
	GLOBAL_DATA_VALUE_TH, TM7_PATH, FULLNAME, NAT_MANE, PV_DESC, AMP_DESC, DEP_NAME, PREAPV_STATUS_CODE, SEND_DATE,
	SEND_COUNT, PREAPV_SEND_STATUS_CODE, SENDPB_DATE, SENDPB_COUNT, PREAPV_SENDPB_STATUS_CODE, APV_STATUS_CODE,
	APV_STATUS, ACTIVE_CODE, ACTIVE, PRIORITY_CODE, APV_DATE, APV_SENDPB_STATUS_CODE, APV_SENDPB_STATUS, CURRENT_NO, RUNNING_YEAR, UPDATE_DATE,
	APV_CHKPIBICS, APV_CHKPIBICS_DATE, APV_CHKPIBICS_USER, APV_CHKPIBICS_REMARK, APV_CHKPB_BY, VISA_NO, APV_REMARK, APV_USER, APV_SEND_STATUS, APV_SEND_STATUS_CODE, APV_BY,
	COMMAND_SEQNO, COMMAND_OTH, CHK_PRE, REASONCD, APV_DEPT, APV_DEPT1, APV_DEPT2, PRINT_EXIST, REASON_DESC, APV_PERMIT_DATE
	;
}
